<?php

$templates['template'] = array(
    'directory_pattern' => 'custom/Extension/modules/{MODULENAME}/Ext/clients/base',
    'modules' => array(
        'Accounts' => 'Account',
        'Bugs' => 'Bug',
        'Calls' => 'Call',
        'Campaigns' => 'Campaign',
        'Cases' => 'Case',
        'Contacts' => 'Contact',
        'Contracts' => 'Contract',
        'Documents' => 'Document',
        'EmailTemplates' => 'EmailTemplate',
        'Emails' => 'Email',
        'EmbeddedFiles' => 'EmbeddedFile',
        'Employees' => 'Employee',
        'ForecastManagerWorksheets' => 'ForecastManagerWorksheet',
        'ForecastWorksheets' => 'ForecastWorksheet',
        'KBContentTemplates' => 'KBContentTemplate',
        'KBContents' => 'KBContent',
        'KBDocuments' => 'KBDocument',
        'Leads' => 'Lead',
        'Meetings' => 'Meeting',
        'Notes' => 'Note',
        'Notifications' => 'Notifications',
        'Opportunities' => 'Opportunity',
        'ProductCategories' => 'ProductCategory',
        'ProductTemplates' => 'ProductTemplate',
        'ProductTypes' => 'ProductType',
        'Products' => 'Product',
        'Project' => 'Project',
        'ProjectTask' => 'ProjectTask',
        'ProspectLists' => 'ProspectList',
        'Prospects' => 'Prospect',
        'Quotes' => 'Quote',
        'Reports' => 'SavedReport',
        'RevenueLineItems' => 'RevenueLineItem',
        'Styleguide' => 'Styleguide',
        'Tags' => 'Tag',
        'Tasks' => 'Task',
        'Teams' => 'Team',
        'UserSignatures' => 'UserSignature',
        'Users' => 'User',
        'WebLogicHooks' => 'WebLogicHook',
        'pmse_Business_Rules' => 'pmse_Business_Rules',
        'pmse_Emails_Templates' => 'pmse_Emails_Templates',
        'pmse_Inbox' => 'pmse_Inbox',
        'pmse_Project' => 'pmse_Project',
    )
);

